### ISSUE TITLE
No recent plays shown even though I have listened to music

### ISSUE THREAD

**Issue by mrondr** [wistoff/legacy-scrobbler#1]
I am shown the "No recent plays. Your Ipod is up to date" message even though I have listened to some music since the last time legacy-scrobbler was used.
I have synced the ipod with itunes before opening legacy-scrobbler, which might be the cause of this.

Should one use legacy-scrobbler before using itunes?

PS: thanks for your tool. It's awesome

**Comment by mrondr** [comment]
Yup, it seems that legacy-scrobbler first works, itunes first wipes the ipod.
I guess that itunes reads the played songs and wipes the record. Kind of makes sense I guess.
Sorry if this is common knowledge, I had no idea. Maybe a couple of words about this can be added in the README?

**Comment by wistoff** [comment]
Thank you for letting me know that this wasn't clear. I added it to the README :)
